## 서버 포트 설정
#server:
#  port: 8081
#
## 데이터베이스 연결 설정
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/petclinic?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 1234
#
#  jpa:
#    show-sql: true
#    format-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#
## 로깅 설정
#logging:
#  level:
#    org.springframework: DEBUG
#
